services:
  - type: web
    name: videochat-api
    runtime: node
    repo: https://github.com/anonpro1337/videochat-platform
    branch: main
    rootDir: apps/api
    buildCommand: NODE_ENV=development pnpm install --no-frozen-lockfile && NODE_ENV=development pnpm --filter @videochat/api exec prisma generate && NODE_ENV=development pnpm --filter @videochat/api build
    startCommand: pnpm --filter @videochat/api start:prod
    healthCheckPath: /api/v1/health
