apiVersion: v1
kind: ConfigMap
metadata:
  name: videochat-config
  namespace: videochat
data:
  NODE_ENV: "production"
  PORT: "4000"
  SOCKET_PORT: "4001"
  HOST: "0.0.0.0"
  AWS_REGION: "us-east-1"
  WEB_APP_URL: "https://chatvibe.app"
  API_URL: "https://chatvibe.app/api/v1"
  SOCKET_URL: "wss://chatvibe.app"
  JWT_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  NEXT_PUBLIC_API_URL: "https://chatvibe.app/api/v1"
  NEXT_PUBLIC_SOCKET_URL: "wss://chatvibe.app"
